### ISSUE TITLE
Allow enforce payload encoding

### ISSUE THREAD

**Issue by tulios** [klarna/phobos#17]
Allow enforce payload encoding per listener, example:

```yml
listeners:
  - handler: Phobos::EchoHandler
    topic: test
    group_id: test-1
    start_from_beginning: true
    max_bytes_per_partition: 524288
    max_concurrency: 1
    force_encoding: UTF_8
```

Where __UTF_8__ is a constant name defined in `Encoding`. We can get the correct encoding with something like:

```ruby
Encoding.get_const(listener_config.force_encoding.to_sym) if listener_config.force_encoding
```

and then encode the payload before we dispatch it to the handler, example:

```ruby
payload = message.value
if listener_config.force_encoding
  encoding = Encoding.get_const(listener_config.force_encoding.to_sym) 
  payload = payload.force_encoding(encoding)
end
```
