### ISSUE TITLE
Configurable commit strategy

### ISSUE THREAD

**Issue by tulios** [klarna/phobos#21]
Currently, we commit after the entire batch is processed, it would be nice to have an option to define this behavior. It could be an option in the listener configuration, example:

``` yml
listeners:
  - handler: Phobos::EchoHandler
    topic: test
    # id of the group that the consumer should join
    group_id: test-1
    commit_strategy: each_batch # each_message
```

we need to give more thought in the naming used.
